package edu.uclm.esi.fakeaccountsbe.tests;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.Point;

import java.util.*;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(OrderAnnotation.class)
public class RegistroCorrectoTest {
	
	private WebDriver driver, driver2;
	private Map<String, Object> vars, vars2;
	JavascriptExecutor jsExecutor, jsExecutor2;

 
  @BeforeAll //@AfterAll
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "D:\\OneDrive - Universidad de Castilla-La Mancha\\4. Cuarto Año\\4.1.1 Tecnologías y Sistemas Web\\Laboratorio\\chromedriver-win64\\chromedriver.exe");  
	  
	ChromeOptions options = new ChromeOptions();
	options.setBinary("D:\\OneDrive - Universidad de Castilla-La Mancha\\4. Cuarto Año\\4.1.1 Tecnologías y Sistemas Web\\Laboratorio\\chrome-win64\\chrome.exe"); 
	options.addArguments("--remote-allow-origins=*");
    
	driver = new ChromeDriver(options);
	new WebDriverWait(driver, Duration.ofSeconds(3));

	jsExecutor = (JavascriptExecutor) driver;
	vars = new HashMap<String, Object>();
	
	driver2 = new ChromeDriver(options);
	new WebDriverWait(driver2, Duration.ofSeconds(3));

	jsExecutor2 = (JavascriptExecutor) driver2;
	vars2 = new HashMap<String, Object>();
	
	driver.get("https://alarcosj.esi.uclm.es/examplesfortesting/");
	driver2.get("https://alarcosj.esi.uclm.es/examplesfortesting/");
	this.pausa(1000);
	
	java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
	int screenWidth = (int) screenSize.getWidth();
	int screenHeight = (int) screenSize.getHeight();
	
	driver.manage().window().setPosition(new Point(0,0));
	driver.manage().window().setSize(new Dimension(screenWidth / 2, screenHeight));
	
	driver2.manage().window().setPosition(new Point((screenWidth/ 2) + 1, 0));
	driver2.manage().window().setSize(new Dimension(screenWidth / 2, screenHeight));
  }
  
  @AfterAll
  public void tearDown() {
    driver.quit();
    driver2.quit();
  }
  
  @Test @Order(0)
  public void testRegistroCorrecto() {
    this.registrar(this.driver, "alex", "alex@alex.com", "Alex1234", "Alex1234");
    
    this.pausa(1000);
    
    String url = driver.getCurrentUrl();
    assertEquals("https://alarcosj.esi.uclm.es/examplesfortesting/angular/login", url);

    //WebElement etiqueta = driver.findElement(By.xpath("/html/body/app-root/div/main/app-login/h2"));
    //assertEquals("Login", etiqueta.getText())
    
  }
  
  @Test @Order(1)
  public void testRegistroIncorrecto() {
    this.registrar(this.driver2, "manuel", "manuel@manuel.com", "Manuel1234", "Manuel123");
    
    this.pausa(1000);
    
    WebElement etiqueta = driver2.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[4]/small"));
    assertEquals("Passwords do not match.", etiqueta.getText());
    
  }

  @Test @Order(2)
  public void testLoginCorrecto() {
	this.login(this.driver, "alex", "Alex1234");
	  
	this.pausa(1000);
	  
	String url = driver.getCurrentUrl();
	assertEquals("https://alarcosj.esi.uclm.es/examplesfortesting/angular/celebration", url);
  }
  
  
  @ParameterizedTest @Order(3)
  @CsvSource({ "alex, alex@alex.com, Alex1234, Alex1234, false",
	  "manuel1, manuel1@manuel.com, Manuel1234, Manuel1234, true",
	  "manuel2, manuel2@manuel.com, Manuel1234, Manuel123, false",
	  "manuel2, manuel2@manuel.com, Manuel1234, Manuel1234, true"})
  void registroMasivo(String nombre, String email, String pwd1, String pwd2, boolean veredictoDePaso) {
	  
	this.irAhome(this.driver);
	
    this.registrar(this.driver, nombre, email, pwd1, pwd2);
  
    this.pausa(1000);
  
	if (veredictoDePaso) {
		this.driver.findElement(By.xpath("/html/body/app-root/div/header/nav/ul/li[2]/a")).click();
	} else {
		 WebElement etiqueta = driver2.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[4]/small"));
		 assertEquals("Passwords do not match.", etiqueta.getText());
	    
	    List<WebElement>cajas = this.driver.findElements(By.tagName("input"));
		cajas.forEach(caja -> caja.clear());
	}
  }

  
  private void irAhome(WebDriver driver) {
	driver.get("https://alarcosj.esi.uclm.es/examplesfortesting/");
  }
  
  private void pausa(int i) {
	try {
		Thread.sleep(i);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
  }
	
  private void registrar(WebDriver driver, String nombre, String email, String pwd1, String pwd2) {
	WebElement botonAngular = driver.findElement(By.xpath("/html/body/div[1]/div/a[1]"));
    botonAngular.click();
    
    this.pausa(1000);
    
    WebElement menuRegistrarse = driver.findElement(By.xpath("/html/body/app-root/div/header/nav/ul/li[2]/a"));
    menuRegistrarse.click();
    
    this.pausa(1000);
    
    WebElement inputNombre = driver.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[1]/input"));
    WebElement inputEmail = driver.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[2]/input"));
    WebElement inputPwd1 = driver.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[3]/input"));
    WebElement inputPwd2 = driver.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[4]/input"));
    WebElement botonRegistrarse = driver.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[5]/button"));

    inputNombre.sendKeys(nombre);
    inputEmail.sendKeys(email);
    inputPwd1.sendKeys(pwd1);
    inputPwd2.sendKeys(pwd2);
    botonRegistrarse.click();
	     
  }
	
  private void login(WebDriver driver, String nombre, String pwd) {
	WebElement cajaNombre = driver.findElement(By.xpath("/html/body/app-root/div/main/app-login/form/div[1]/input"));
	WebElement cajaPwd = driver.findElement(By.xpath("/html/body/app-root/div/main/app-login/form/div[2]/input"));
  
	cajaNombre.sendKeys(nombre);
	cajaPwd.sendKeys(pwd);
  
	WebElement botonLogin = driver.findElement(By.xpath("/html/body/app-root/div/main/app-login/form/div[3]/button"));
	botonLogin.click();
  }
}
